plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.proxyclienthttpltm'
    compileSdkVersion 34

    defaultConfig {
        applicationId "com.example.proxyclienthttpltm"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"

    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
}